### ISSUE TITLE
some bugs die or when opening the nuclear button

### ISSUE THREAD

**Issue by Galinhadofuturo** [Thundermaker300/RoundStats#1]
![image](https://user-images.githubusercontent.com/96889354/202864375-9fb8e5e3-74ed-4bd6-9f19-80bb4e530c19.png)
![image](https://user-images.githubusercontent.com/96889354/202864414-046c89b2-de83-469b-b12c-0b6a997c1f4a.png)

**Comment by Thundermaker300** [comment]
Didn't see this until just now, but I will lookie, thx

**Comment by Thundermaker300** [comment]
I put in some null player checks. Not sure why players would be null in these cases, but will no longer error.
